/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Pin_A_OUT.h"
#include "Pin_A_OUT_aliases.h"
#include "Pin_B_OUT.h"
#include "Pin_B_OUT_aliases.h"
#include "Pin_C_OUT.h"
#include "Pin_C_OUT_aliases.h"
#include "Pin_D_OUT.h"
#include "Pin_D_OUT_aliases.h"
#include "Pin_S0.h"
#include "Pin_S0_aliases.h"
#include "Pin_S1.h"
#include "Pin_S1_aliases.h"
#include "Pin_SHIFT_L.h"
#include "Pin_SHIFT_L_aliases.h"
#include "Pin_SHIFT_R.h"
#include "Pin_SHIFT_R_aliases.h"
#include "Pin_INPUT_A.h"
#include "Pin_INPUT_A_aliases.h"
#include "Pin_INPUT_B.h"
#include "Pin_INPUT_B_aliases.h"
#include "Pin_INPUT_C.h"
#include "Pin_INPUT_C_aliases.h"
#include "Pin_INPUT_D.h"
#include "Pin_INPUT_D_aliases.h"
#include "Pin_CL.h"
#include "Pin_CL_aliases.h"
#include "Pin_TRUE.h"
#include "Pin_TRUE_aliases.h"
#include "UART_1.h"
#include "UART_1_SPI_UART.h"
#include "UART_1_PINS.h"
#include "UART_1_SPI_UART_PVT.h"
#include "UART_1_PVT.h"
#include "UART_1_BOOT.h"
#include "UART_1_SCBCLK.h"
#include "UART_1_tx.h"
#include "UART_1_tx_aliases.h"
#include "UART_1_rx.h"
#include "UART_1_rx_aliases.h"
#include "cy_em_eeprom.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"

/*[]*/

